# Indexing & Slicing

## Indexing (single elements)

### 1-D array indexing

In [2]:
import numpy as np
a = np.array([10, 20, 30, 40, 50])

print(a[0])  # 10
print(a[-1]) # 50 (last element)


10
50


### 2-D array indexing

You access elements by `[row, column]`.


In [3]:
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(b[0, 1])  # 2  (1st row, 2nd column)
print(b[2, 0])  # 7  (3rd row, 1st column)



2
7


### 3-D array indexing

Add more indices: `[depth, row, column]`.


In [4]:
c = np.array([[[1, 2], [3, 4]],
              [[5, 6], [7, 8]]])

print(c[0, 1, 1]) # 4
print(c[1, 0, 0]) # 5


4
5


## Slicing (subarrays)

The format is always:

```
[start:stop:step]
```

like Python lists.

---

### 1-D slicing


In [5]:

a = np.array([10, 20, 30, 40, 50])
print(a[1:4])   # [20 30 40]
print(a[:3])    # [10 20 30]
print(a[::2])   # [10 30 50]
print(a[::-1])  # [50 40 30 20 10] (reversed)


[20 30 40]
[10 20 30]
[10 30 50]
[50 40 30 20 10]


### 2-D slicing

You slice **rows** and **columns** separately:

```
array[rows, columns]
```


In [6]:
b = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9,10,11,12]])

print(b[0:2, 1:3])
# [[2 3]
#  [6 7]]

print(b[:, 2])
# [ 3  7 11] (all rows, 3rd column)

print(b[1, :])
# [5 6 7 8] (2nd row, all columns)


[[2 3]
 [6 7]]
[ 3  7 11]
[5 6 7 8]


### Fancy slicing: steps

In [7]:
print(a)
print(a[[0, 2, 4]])
# [10 30 50]

print(b[[0, 2], [1, 2]])
# [2 9]
print(b[::2, ::2])
# [[ 1  3]
#  [ 9 11]]


[10 20 30 40 50]
[10 30 50]
[ 2 11]
[[ 1  3]
 [ 9 11]]


## Boolean indexing (masking)

This is powerful: select elements by condition.

In [8]:
a = np.array([10, 15, 20, 25, 30])
mask = a > 18
print(mask)
# [False False  True  True  True]

print(a[mask])
# [20 25 30]


[False False  True  True  True]
[20 25 30]


In [9]:
print(a[a % 2 == 0])
# [10 20 30]


[10 20 30]


## Ellipsis (...) in Indexing
The ellipsis (...) can be used to select all dimensions which are not explicitly mentioned. This is helpful in multidimensional arrays when we don’t want to specify every dimension.

In [10]:
import numpy as np

cube = np.random.rand(4, 4, 5)
print(cube)
print(cube[..., 0])

[[[0.64068788 0.35463323 0.07361306 0.73561004 0.86124927]
  [0.07211698 0.70635867 0.21796022 0.39004693 0.95396716]
  [0.11114573 0.57803318 0.38593829 0.77215311 0.68364156]
  [0.09329269 0.50786639 0.59521239 0.23066477 0.6618695 ]]

 [[0.07774991 0.04135257 0.27006478 0.69666771 0.27602285]
  [0.47451478 0.79778106 0.64638099 0.2796344  0.01916674]
  [0.18643002 0.98504479 0.91183996 0.65182989 0.27373922]
  [0.82998368 0.8927755  0.27910095 0.85268777 0.15013722]]

 [[0.5604401  0.09924574 0.00211429 0.92271191 0.14809969]
  [0.46092581 0.67856731 0.88969221 0.13339392 0.93065717]
  [0.57146311 0.71369953 0.36006981 0.95421394 0.63702896]
  [0.6789245  0.93513399 0.86281369 0.75771804 0.05154252]]

 [[0.71446863 0.08816159 0.54880957 0.55931481 0.12490957]
  [0.94452834 0.12667376 0.51008388 0.74887827 0.59762433]
  [0.83987725 0.77574022 0.73904555 0.4741748  0.14848751]
  [0.63647179 0.50725891 0.5165833  0.78318334 0.5741249 ]]]
[[0.64068788 0.07211698 0.11114573 0.09329269]
 

## Quick summary table

| Operation          | Example       | Result                 |
| ------------------ | ------------- | ---------------------- |
| Single index       | `a[1]`        | Single element         |
| 2D access          | `b[1,2]`      | Element at row=1,col=2 |
| Slice 1D           | `a[1:4]`      | Elements 1 to 3        |
| Slice rows/columns | `b[0:2, 1:3]` | Submatrix              |
| All rows in col 2  | `b[:,2]`      | 1D array of column     |
| All cols in row 1  | `b[1,:]`      | 1D array of row        |
| Steps              | `a[::2]`      | Every 2nd element      |
| Reverse            | `a[::-1]`     | Array reversed         |
| Boolean mask       | `a[a>20]`     | Elements > 20          |

In [11]:
c = np.arange(24).reshape(2,3,4)
# shape (2,3,4) -> 2 blocks, each 3x4
print(c)
print(c[:, 1, :])
# Picks the 2nd row from each block


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[ 4  5  6  7]
 [16 17 18 19]]


In [12]:
# Importing Numpy module
import numpy as np

# Creating a 4X4 2-D Numpy array
arr = np.array([[1, 20, 3, 1], 
                [40, 5, 66, 7], 
                [70, 88, 9, 11],
               [80, 100, 50, 77]])

print("Given Array :")
print(arr)

# Access the Last three rows of array
res_arr = arr[[1,2]]
print("\nAccessed Rows :")
print(res_arr)

Given Array :
[[  1  20   3   1]
 [ 40   5  66   7]
 [ 70  88   9  11]
 [ 80 100  50  77]]

Accessed Rows :
[[40  5 66  7]
 [70 88  9 11]]


## Accessing the First and Last rows of 3-D NumPy array

In [13]:
n_arr = np.array([[[10, 25, 70], [30, 45, 55], [20, 45, 7]], 
                  [[50, 65, 8], [70, 85, 10], [11, 22, 33]],
                 [[19, 69, 36], [1, 5, 24], [4, 20, 96]]])

In [14]:
n_arr[:,[0,2]]

array([[[10, 25, 70],
        [20, 45,  7]],

       [[50, 65,  8],
        [11, 22, 33]],

       [[19, 69, 36],
        [ 4, 20, 96]]])

In [15]:
import numpy as np

arr = np.array([[ 0,  1,  2,  3],
                [10, 11, 12, 13],
                [20, 21, 22, 23],
                [30, 31, 32, 33],
                [40, 41, 42, 43]])


In [ ]:
arr[1:3,[1,2]]
'''
array([[11, 12],
       [21, 22]])       
'''
arr[1, 2]
'''
12
'''
arr[1:4, 1:3]
'''
array([[11, 12],
       [21, 22],
       [31, 32]])
'''
arr[:3, [0,2]]
'''
array([[ 0,  2],
       [10, 12],
       [20, 22]])
'''
arr[[0, 2, 4], [1, 2, 3]] # this gives elements at positions (0,1), (2,2), (4,3))
'''
array([ 1, 22, 43])
'''
arr[::2, ::2]
'''
array([[ 0,  2],
       [20, 22],
       [40, 42]])
'''
arr[:, 2]
'''
array([ 2, 12, 22, 32, 42])
'''
arr[::-1,1:4]
'''
array([[41, 42, 43],
       [31, 32, 33],
       [21, 22, 23],
       [11, 12, 13],
       [ 1,  2,  3]])
'''

In [18]:
arr = np.array([[ 0,  1,  2,  3],
                [10, 11, 12, 13],
                [20, 21, 22, 23],
                [30, 31, 32, 33],
                [40, 41, 42, 43]])

In [ ]:
arr[[1,3]]

'''array([[10, 11, 12, 13],
       [30, 31, 32, 33]])
'''

array([[10, 11, 12, 13],
       [30, 31, 32, 33]])

## Solutions

## Basic indexing

### `arr[3,1]`

```python
arr[3,1]
# -> 31
```

(4th row, 2nd column)

---

### `arr[-1,-2]`

```python
arr[-1,-2]
# -> 42
```

(last row, 2nd last column)

---

### `arr[5,1]`

```python
# IndexError: index 5 is out of bounds for axis 0 with size 5
```

Because rows only go from `0` to `4`.

---

## Slicing

### `arr[1:4, 2:4]`

```python
arr[1:4, 2:4]
# -> array([[12, 13],
#           [22, 23],
#           [32, 33]])
```

---

### `arr[:3, :2]`

```python
arr[:3, :2]
# -> array([[ 0,  1],
#           [10, 11],
#           [20, 21]])
```

---

### Last 2 rows and last 3 columns

```python
arr[-2:, -3:]
# -> array([[31, 32, 33],
#           [41, 42, 43]])
```

---

## Steps / strides

###  `arr[::2, ::2]`

```python
arr[::2, ::2]
# -> array([[ 0,  2],
#           [20, 22],
#           [40, 42]])
```

(every other row & column)

---

### Reverse rows

```python
arr[::-1, :]
# -> array([[40,41,42,43],
#           [30,31,32,33],
#           [20,21,22,23],
#           [10,11,12,13],
#           [ 0, 1, 2, 3]])
```

---

### Reverse both rows & columns

```python
arr[::-1, ::-1]
# -> array([[43,42,41,40],
#           [33,32,31,30],
#           [23,22,21,20],
#           [13,12,11,10],
#           [ 3, 2, 1, 0]])
```

---

## Boolean indexing

### `arr[arr > 25]`

```python
arr[arr > 25]
# -> array([30,31,32,33,40,41,42,43])
```

---

### Elements divisible by 10

```python
arr[arr % 10 == 0]
# -> array([ 0,10,20,30,40])
```

---

### Set all elements >30 to 999

```python
arr[arr > 30] = 999
# arr now becomes:
# [[  0   1   2   3]
#  [ 10  11  12  13]
#  [ 20  21  22  23]
#  [ 30  31  32  33]
#  [ 40  41  42  43]]

# after assignment
# [[  0   1   2   3]
#  [ 10  11  12  13]
#  [ 20  21  22  23]
#  [ 30 999 999 999]
#  [999 999 999 999]]
```

---

## Fancy indexing

### `arr[[0,2,4], [1,2,3]]`

```python
arr[[0,2,4], [1,2,3]]
# -> array([ 1,22,43])
```

It pulls elements from positions: `(0,1)`, `(2,2)`, `(4,3)`.

---

### Get rows 1 & 3

```python
arr[[1,3]]
# -> array([[10,11,12,13],
#           [30,31,32,33]])
```

---

## Using `np.ix_`

### ➡️ 15. Using `np.ix_`

```python
rows = [1,3]
cols = [0,2]
arr[np.ix_(rows, cols)]
# -> array([[10,12],
#           [30,32]])
```

---

### 16. Why `arr[[1,3]][:,[0,2]]` might differ

* `arr[[1,3]]` first gives a **(2,4) array**, then `[:,[0,2]]` works on this smaller slice.
* It might not match intended indices if you meant to pick original global `(1,0)` and `(3,2)`.

`np.ix_` always references **original indices together**, building a true submatrix.

---

## 1D vs 2D slicing

### 2nd column as flat array

```python
arr[:,1]
# -> array([ 1,11,21,31,41])
```

---

### As column matrix (5,1)

```python
arr[:,1:2]
# -> array([[ 1],
#           [11],
#           [21],
#           [31],
#           [41]])
```

---

## 3D array practice

Given:

```python
b = np.arange(24).reshape(2,3,4)
```

---

### ➡️ 19. `b[1,2,3]`

```python
b[1,2,3]
# -> 23
```

2nd block, 3rd row, 4th column.

---

### Last row of each block

```python
b[:, -1, :]
# -> array([[ 8,  9, 10, 11],
#           [20, 21, 22, 23]])
```

---

## Bonus challenge solution

### Every other row & last-to-first columns

```python
arr[::2, ::-2]
# -> array([[ 3,  1],
#           [23, 21],
#           [43, 41]])
```