```{contents}
```

## Linear Algebra Methods

In [17]:
import numpy as np

# Matrix creation
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
x = np.array([1, 2])


### Element-wise operations

In [18]:
print("A + B:\n", A + B)
print("A - B:\n", A - B)
print("A * B (element-wise):\n", A * B)
print("A / B:\n", A / B)
print("A squared:\n", A ** 2)


A + B:
 [[ 6  8]
 [10 12]]
A - B:
 [[-4 -4]
 [-4 -4]]
A * B (element-wise):
 [[ 5 12]
 [21 32]]
A / B:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
A squared:
 [[ 1  4]
 [ 9 16]]


### Matrix multiplication

In [19]:
print("A @ B (matrix multiplication):\n", A @ B)
print("np.dot(A, B):\n", np.dot(A, B))

A @ B (matrix multiplication):
 [[19 22]
 [43 50]]
np.dot(A, B):
 [[19 22]
 [43 50]]


### Transpose

In [20]:
A.T


array([[1, 3],
       [2, 4]])

### Reshape and Flatten

In [21]:
print("A reshaped to (4,1):\n", A.reshape(4,1))
print("A flattened:\n", A.flatten())


A reshaped to (4,1):
 [[1]
 [2]
 [3]
 [4]]
A flattened:
 [1 2 3 4]



### Inverse and Determinant


In [22]:

print("Inverse of A:\n", np.linalg.inv(A))
print("Determinant of A:", np.linalg.det(A))



Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant of A: -2.0000000000000004


### Solving Linear Systems

In [23]:
print("Solution to Ax = x:", np.linalg.solve(A, x))


Solution to Ax = x: [0.  0.5]


### Eigenvalues and Eigenvectors

In [24]:
eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)



Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


### Singular Value Decomposition (SVD)

In [25]:
U, S, Vt = np.linalg.svd(A)
print("SVD U:\n", U)
print("SVD S:", S)
print("SVD Vt:\n", Vt)


SVD U:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
SVD S: [5.4649857  0.36596619]
SVD Vt:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


### Norm and Trace

In [26]:
print("Frobenius norm:", np.linalg.norm(A))
print("Trace (sum of diagonal):", np.trace(A))


Frobenius norm: 5.477225575051661
Trace (sum of diagonal): 5


### Diagonal Operations

In [27]:
print("Extract diagonal:", np.diag(A))
print("Create diagonal matrix:", np.diag([10, 20]))


Extract diagonal: [1 4]
Create diagonal matrix: [[10  0]
 [ 0 20]]


---

### Triangular Matrices


In [28]:
print("Upper triangle:\n", np.triu(A))
print("Lower triangle:\n", np.tril(A))


Upper triangle:
 [[1 2]
 [0 4]]
Lower triangle:
 [[1 0]
 [3 4]]


### Outer and Inner Products

In [29]:
print("Outer product of x and itself:\n", np.outer(x, x))
print("Inner product (dot) of x with itself:", np.inner(x, x))


Outer product of x and itself:
 [[1 2]
 [2 4]]
Inner product (dot) of x with itself: 5
