```{contents}
```

# Functions


##  Reduction / Aggregation Functions

These **reduce an array** to a single value (or smaller shape) by applying operations along an axis.

Examples: `np.sum`, `np.mean`, `np.min`, `np.max`, `np.std`, `np.var`, `np.prod`



In [6]:
import numpy as np

arr = np.array([3, 1, 4, 1, 5])

print("Sum:", np.sum(arr))         ## 14
print("Mean:", np.mean(arr))       ## 2.8
print("Min:", np.min(arr))         ## 1
print("Max:", np.max(arr))         ## 5
print("Product:", np.prod(arr))    ## 60


Sum: 14
Mean: 2.8
Min: 1
Max: 5
Product: 60




These are called **aggregation functions** because they **aggregate** values across elements.

---

## Cumulative Functions

Instead of reducing, they keep track of a **running accumulation**.

Examples: `np.cumsum`, `np.cumprod`, `np.cummax`, `np.cummin`



In [7]:

arr = np.array([1, 2, 3, 4])

print("Cumulative Sum:", np.cumsum(arr))     
print("Cumulative Product:", np.cumprod(arr))


Cumulative Sum: [ 1  3  6 10]
Cumulative Product: [ 1  2  6 24]




---

## Indexing / Location Functions

These **find indices** based on certain conditions.

Examples:

* `np.argmin` → index of min
* `np.argmax` → index of max
* `np.where` → indices where condition is true
* `np.nonzero` → indices of nonzero values



In [8]:
arr = np.array([10, 20, 5, 30])

print("Index of Min:", np.argmin(arr))   ## 2
print("Index of Max:", np.argmax(arr))   ## 3

print("Where > 15:", np.where(arr > 15))   ## (array([1, 3]),)
print("Nonzero Indices:", np.nonzero(arr)) ## (array([0, 1, 2, 3]),)


Index of Min: 2
Index of Max: 3
Where > 15: (array([1, 3]),)
Nonzero Indices: (array([0, 1, 2, 3]),)




---

## Filtering Functions

Used to **select elements** from arrays based on conditions.

Examples: Boolean indexing, `np.where`



In [9]:
arr = np.array([1, 2, 3, 4, 5, 6])

## Filter even numbers
print("Even numbers:", arr[arr % 2 == 0])  ## [2 4 6]

## Using where
print("Replace odd with 0:", np.where(arr % 2 == 0, arr, 0))  ## [0 2 0 4 0 6]


Even numbers: [2 4 6]
Replace odd with 0: [0 2 0 4 0 6]




---

## Sorting Functions

Used to **order array elements**.

Examples:

* `np.sort` → sorted array
* `np.argsort` → indices of sorted order
* `np.partition` → partial sorting



In [10]:

arr = np.array([10, 5, 8, 3])

print("Sorted:", np.sort(arr))         ## [3 5 8 10]
print("Argsort:", np.argsort(arr))     ## [3 1 2 0]


print("Partition:", np.partition(arr, 2))  ## [3 5 8 10]


Sorted: [ 3  5  8 10]
Argsort: [3 1 2 0]
Partition: [ 3  5  8 10]


## Other Functions

In [21]:
a = np.array([1, 2, 3])                  # Basic array
b = np.zeros((2,3))                      # 2x3 zeros
c = np.ones((2,2))                       # 2x2 ones
d = np.arange(1,6)                       # [1 2 3 4 5]
e = np.linspace(0,1,5)                   # 5 points [0. ,0.25,0.5,0.75,1.]
f = np.eye(3)                            # 3x3 Identity matrix
g = np.full((2,3), 7)                    # 2x3 filled with 7
h = np.tile([1,2], (2,3))                # Repeat pattern



---

## Inspection / Information




arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)     # (2,3)
print(arr.ndim)      # 2
print(arr.size)      # 6
print(arr.dtype)     # int64 (depends on system)




---

## 3️⃣ Mathematical Functions



In [20]:
x = np.array([0, np.pi/2, np.pi])
print(np.sin(x))      # [0. 1. 0.]
print(np.log([1, np.e]))   # [0. 1.]
print(np.exp([0,1]))       # [1. 2.718...]
print(np.floor([1.7, -1.7])) # [ 1. -2.]
print(np.ceil([1.2, -1.2]))  # [ 2. -1.]
print(np.abs([-2, 3]))       # [2 3]


[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[0. 1.]
[1.         2.71828183]
[ 1. -2.]
[ 2. -1.]
[2 3]




---

## 4️⃣ Random Functions



In [19]:
print(np.random.randint(0,10,5))   # 5 random ints [0,9]
print(np.random.rand(3))           # 3 random floats [0,1)
print(np.random.normal(0,1,5))     # Normal distribution
print(np.random.choice([1,2,3], 5))# Random choice


[4 9 0 3 2]
[0.64176275 0.99256909 0.65817346]
[-0.96297176  1.38584399  0.43958962  1.73826268  0.98553755]
[2 1 2 3 3]




---

## 5️⃣ Linear Algebra



In [18]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(np.dot(A,B))             # Matrix multiplication
print(np.linalg.det(A))        # Determinant = -2
print(np.linalg.inv(A))        # Inverse matrix
vals, vecs = np.linalg.eig(A)  # Eigenvalues & Eigenvectors
print(np.linalg.norm(A))       # Norm



[[19 22]
 [43 50]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
5.477225575051661


---

## 6️⃣ Reshaping & Combining



In [17]:
arr = np.arange(6).reshape(2,3)
print(arr)

print(np.ravel(arr))         # Flatten [0 1 2 3 4 5]
print(arr.flatten())         # Same as ravel
print(np.expand_dims(arr, axis=0).shape)  # Add dimension

# Stacking
x = np.array([1,2,3])
y = np.array([4,5,6])
print(np.hstack([x,y]))      # [1 2 3 4 5 6]
print(np.vstack([x,y]))      # [[1 2 3],[4 5 6]]


[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]
[0 1 2 3 4 5]
(1, 2, 3)
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]




---

## 7️⃣ Indexing / Selection



In [16]:
arr = np.arange(10)
print(arr[arr>5])            # Boolean indexing -> [6 7 8 9]
print(arr[[1,3,5]])          # Fancy indexing -> [1 3 5]
print(np.take(arr,[2,4,6]))  # Take -> [2 4 6]


[6 7 8 9]
[1 3 5]
[2 4 6]



---

## 8️⃣ Set Operations



In [15]:
a = np.array([1,2,3,4])
b = np.array([3,4,5,6])

print(np.union1d(a,b))       # [1 2 3 4 5 6]
print(np.intersect1d(a,b))   # [3 4]
print(np.setdiff1d(a,b))     # [1 2]
print(np.setxor1d(a,b))      # [1 2 5 6]

[1 2 3 4 5 6]
[3 4]
[1 2]
[1 2 5 6]



---

## 9️⃣ Sorting & Searching


In [14]:
arr = np.array([3,1,2])
print(np.sort(arr))          # [1 2 3]
print(np.argsort(arr))       # indices [1 2 0]
print(np.where(arr>1))       # Indices where condition met
print(np.nonzero(arr))       # Indices of non-zero
print(np.searchsorted([1,3,5], 4))  # position -> 2


[1 2 3]
[1 2 0]
(array([0, 2]),)
(array([0, 1, 2]),)
2



---

## 🔟 Statistics



In [13]:
data = np.array([1,2,3,4,5])
print(np.mean(data))      # 3.0
print(np.median(data))    # 3.0
print(np.std(data))       # 1.414
print(np.var(data))       # 2.0
print(np.percentile(data, 50))  # 3.0
print(np.histogram(data)) # histogram counts


3.0
3.0
1.4142135623730951
2.0
3.0
(array([1, 0, 1, 0, 0, 1, 0, 1, 0, 1]), array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ]))




---

## 1Bitwise & Logic


In [12]:
a = np.array([0,1,1])
b = np.array([1,1,0])

print(np.bitwise_and(a,b))  # [0 1 0]
print(np.bitwise_or(a,b))   # [1 1 1]
print(np.any(a))            # True
print(np.all(a))            # False
print(np.isin([1,2,3],[2,3,4])) # [False True True]


[0 1 0]
[1 1 1]
True
False
[False  True  True]



---

## Utility



In [11]:
arr = np.array([1,2,3,10])
print(np.clip(arr,2,5))   # [2 2 3 5]

M = np.array([[1,2],[3,4]])
print(np.diag(M))         # [1 4]

print(np.triu(M))         # upper triangle
print(np.tril(M))         # lower triangle

x = np.array([0,1,2])
y = np.array([0,1,2])
X, Y = np.meshgrid(x,y)
print(X)   # grid matrix

print(np.pad([1,2,3], (2,3), 'constant'))


[2 2 3 5]
[1 4]
[[1 2]
 [0 4]]
[[1 0]
 [3 4]]
[[0 1 2]
 [0 1 2]
 [0 1 2]]
[0 0 1 2 3 0 0 0]


---

**Summary:**

* **Reduction / Aggregation** → collapse to single value (`sum`, `mean`, `min`, `max`)
* **Cumulative** → running totals (`cumsum`, `cumprod`)
* **Indexing / Location** → find indices (`argmin`, `argmax`, `where`, `nonzero`)
* **Filtering** → select values (`boolean indexing`, `where`)
* **Sorting** → reorder values (`sort`, `argsort`, `partition`)

