```{contents}
```

# Stacking & Splitting

## Stacking

---

### 1. **Vertical stacking (`vstack`)**

Stacks arrays **row-wise** (axis = 0).



In [13]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.vstack((a,b)))


[[1 2 3]
 [4 5 6]]


Shape `(2,3)` → rows stacked.

---

### Horizontal stacking (`hstack`)

Stacks arrays **column-wise** (axis = 1 for 2D).


In [14]:
print(np.hstack((a,b)))

# If 2D: columns are joined

x = np.array([[1],[2],[3]])
y = np.array([[4],[5],[6]])
print(np.hstack((x,y)))


[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]


### Depth stacking (`dstack`)

Stacks along the **third axis** (depth).


In [15]:
print(np.dstack((a,b)))


[[[1 4]
  [2 5]
  [3 6]]]




Shape `(1,3,2)`.

---

### Column stacking (`column_stack`)

Stacks 1D arrays as **columns** into a 2D array.



In [16]:
print(np.column_stack((a,b)))


[[1 4]
 [2 5]
 [3 6]]




Equivalent to `np.c_[a,b]`.

---

### Row stacking (`row_stack`)

Stacks 1D arrays as **rows** into a 2D array.



In [17]:

print(np.row_stack((a,b)))


# Equivalent to `np.vstack((a,b))`.


[[1 2 3]
 [4 5 6]]


C:\Users\sangouda\AppData\Local\Temp\ipykernel_36800\1414643688.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack((a,b)))



---

### Generic stacking (`stack`)

Adds a **new axis** at a specified position.



In [18]:

print(np.stack((a,b), axis=0))

print(np.stack((a,b), axis=1))


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]




* `axis=0` → row-wise
* `axis=1` → column-wise

---

✅ **Summary**

* `vstack` / `row_stack`: stack as rows
* `hstack`: stack as columns
* `dstack`: stack into depth (3rd axis)
* `column_stack`: 1D arrays → columns of 2D
* `stack`: flexible, adds a new axis anywhere



## Splitting

### Horizontal split (`hsplit`)

Splits along **columns** (axis = 1).



In [24]:
import numpy as np

a = np.arange(16).reshape(4,4)
print("Array:\n", a)

# Split into 2 equal parts (along columns)
print(np.hsplit(a, 2))


Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]



---

### Vertical split (`vsplit`)

Splits along **rows** (axis = 0).



In [25]:
print(np.vsplit(a, 2))


[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]



---

### Depth split (`dsplit`)

Splits along the **third axis** (depth).


In [21]:
b = np.arange(27).reshape(3,3,3)
print(np.dsplit(b, 3))


[array([[[ 0],
        [ 3],
        [ 6]],

       [[ 9],
        [12],
        [15]],

       [[18],
        [21],
        [24]]]), array([[[ 1],
        [ 4],
        [ 7]],

       [[10],
        [13],
        [16]],

       [[19],
        [22],
        [25]]]), array([[[ 2],
        [ 5],
        [ 8]],

       [[11],
        [14],
        [17]],

       [[20],
        [23],
        [26]]])]



---

### Generic split (`split`)

More flexible → choose **axis**.



In [22]:
c = np.arange(9).reshape(3,3)
print(np.split(c, 3, axis=1))


[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]



---

### Array\_split

Like `split`, but allows **unequal division**.

In [23]:
d = np.arange(10)
print(np.array_split(d, 3))

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


✔ Unlike `split`, it won’t throw an error if sizes don’t divide evenly.

---

**Summary**

* `hsplit` → split by columns
* `vsplit` → split by rows
* `dsplit` → split by depth (3D)
* `split` → generic, axis-specific, but requires equal division
* `array_split` → like `split`, but allows unequal sizes