```{contents}
```

# Broadcasting 

NumPy broadcasting is a powerful mechanism that allows NumPy to work with arrays of different shapes during arithmetic operations. It simplifies code and improves performance by avoiding unnecessary data replication.

---

In [3]:
import numpy as np

A = np.array([1, 2, 3])
print(A + 10)


[11 12 13]


## Broadcasting Rules

Broadcasting follows a set of rules to determine if two arrays are compatible for element-wise operations. If the arrays do not have the same shape, NumPy compares their shapes element-wise, starting from the trailing dimensions.

In [4]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])
print(A + B)


[[11 22 33]
 [14 25 36]]


### Example 1: Adding a Scalar to an Array

When a scalar is added to an array, the scalar is broadcast to the shape of the array.

In [5]:
C = np.array([[1],
              [2],
              [3]])

D = np.array([10, 20, 30])
print(C + D)


[[11 21 31]
 [12 22 32]
 [13 23 33]]


### Example 2: Adding Arrays of Different Shapes

NumPy can automatically expand the smaller array to match the shape of the larger one, following broadcasting rules.

In [11]:
# A = np.array([1, 2, 3])
# B = np.array([10, 20])
# A + B


### Broadcasting Limitations

Not all shapes are compatible for broadcasting. If the rules are not met, NumPy will raise a `ValueError`.

In [10]:
A

array([1, 2, 3])

In [9]:
# for i in range(len(A)):
#     C[i] = A[i] + B

## Summary

- Broadcasting allows NumPy to perform operations on arrays of different shapes.
- It follows specific rules to determine compatibility.
- Broadcasting simplifies code and improves performance.

In [13]:
np.array([[1, 2], [3, 4]]).shape
np.array([10, 20]).shape

(2,)