```{contents}
```

# Arithmetic Operations

| Operator | Function      | Meaning                     |
| -------- | ------------- | --------------------------- |
| `+`      | `np.add`      | element-wise addition       |
| `-`      | `np.subtract` | element-wise subtraction    |
| `*`      | `np.multiply` | element-wise multiplication |
| `/`      | `np.divide`   | element-wise division       |
| `**`     | `np.power`    | element-wise exponent       |
| `%`      | `np.mod`      | element-wise modulus        |

---

## Examples of arithmetic operations

---

### Element-wise addition


In [3]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

c = a + b
print(c)  # [11 22 33]


[11 22 33]




This is **not matrix addition**, it’s adding each element in `a` to each element in `b`.

---

### Element-wise multiplication


In [4]:
d = a * b
print(d)  # [10 40 90]


[10 40 90]




It multiplies `1*10`, `2*20`, `3*30`.

---

### Element-wise power


In [5]:
print(a ** 2)  # [1 4 9]

[1 4 9]



### Element-wise division

In [6]:
print(b / a)  # [10. 10. 10.]

[10. 10. 10.]




---

### Broadcasting makes this powerful

You can mix arrays of **different shapes**, and NumPy will broadcast:


In [7]:
M = np.array([[1, 2, 3],
              [4, 5, 6]])

print(M + 10)


[[11 12 13]
 [14 15 16]]



`10` is broadcast across each element.

Output:

```
[[11 12 13]
 [14 15 16]]
```

---

## More advanced functions

NumPy also provides **universal functions (ufuncs)** which work element-wise:


In [8]:
print(np.sqrt(a))     # element-wise square root
print(np.exp(a))      # e^x
print(np.sin(a))      # sine
print(np.log(a))      # natural logarithm


[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.84147098 0.90929743 0.14112001]
[0.         0.69314718 1.09861229]


## Comparison operations also work element-wise

In [9]:

print(a > 1)   # [False True True]
print(a == 2)  # [False True False]


[False  True  True]
[False  True False]


It gives a **boolean array**.



---

### In-place vs out-of-place operations

```python
a += 5    # modifies `a` in place
```

vs

```python
b = a + 5  # creates a new array
```

---

**Summary table**

| Expression  | Meaning                     |
| ----------- | --------------------------- |
| `a + b`     | element-wise addition       |
| `a - b`     | element-wise subtraction    |
| `a * b`     | element-wise multiplication |
| `a / b`     | element-wise division       |
| `a ** 2`    | element-wise power          |
| `np.sin(a)` | element-wise sine           |
| `a > 2`     | element-wise comparison     |

## Flattening the Array

### `ravel()`

Returns a **flattened view** if possible, otherwise a copy.

```python
import numpy as np

a = np.array([[1,2],[3,4]])
print(a.ravel())   # [1 2 3 4]
```

* Default: row-major (C-order).
* Can specify order: `a.ravel(order='F')` → column-major flatten.

---

### `flatten()`

Always returns a **copy** of the data.

```python
b = a.flatten()
print(b)   # [1 2 3 4]
```

* Modifying `b` will not affect `a`.

---

### `reshape(-1)`

General method using `reshape`.

```python
c = a.reshape(-1)
print(c)   # [1 2 3 4]
```

* Returns a view when possible (like `ravel`).

---

### `np.flat`

Returns an **iterator** over the array in flattened order.

```python
for x in a.flat:
    print(x, end=" ")
# 1 2 3 4
```

---

### Differences

| Method        | View/Copy        | Notes                      |
| ------------- | ---------------- | -------------------------- |
| `ravel()`     | View if possible | Fastest, memory-efficient  |
| `flatten()`   | Always copy      | Safe but uses more memory  |
| `reshape(-1)` | View if possible | Most general reshape trick |
| `flat`        | Iterator         | For looping element-wise   |

